city = {
    "ID": "标识",
    "Room": "推演室ID",
    "UserID": "UserID",
    "UserFlag": "UserID",
    "CityIco": '所属方',
    "Flag": 'Flag',
    "CityName": '地点名称',
    'CityRot': 'CityRot',
    'MapID': '六角格',
    'L1': 'L1',
    'L2': 'L2',
    'L3': 'L3',
    'L4': 'L4',
    'L5': 'L5',
    'L6': 'L6',
    'C0': 'C0',
    'C1': '分值',
    'C2': 'C2',
    'C3': 'C3',
    'Mark': 'Mark',
    'Army': 'Army',
    'Scenario': 'Scenario',
    'Area': '地区 河北',
    'Level': '比赛级别 预赛',
    'Scale': '比赛规模 个人'
}
event = {
    'DateAndTime'     :'时间',
    'StageID'         :'阶段ID（一共6个回合，24个阶段）',
    'TimeID'          :'一个阶段倒计时所在的秒（前15秒间瞄，后15秒最终射击）',
    'ObjID'           :'棋子ID',
    'ObjRot'          :'记录棋子当前的角度',
    'ObjPass'         :'回放棋子是否处于行军状态 0：未行军，1：行军',
    'D3'              :'如果是行军状态，当前行军了多少格',
    'ObjHide'         :'回放棋子是否处于掩蔽状态 0：未掩蔽，1：掩蔽',
    'ObjKeep'         :'回放棋子是否处于被压制状态 0：正常，1：被压制',
    'ObjTire'         :'回放棋子是否处于疲劳状态 0：正常，1：1级疲劳，2：2级疲劳',
    'ObjRound'        :'棋子该阶段是否机动过 0：未机动，1：已机动',
    'ObjAttack'       :'棋子该阶段是否射击过 0：未射击，1：已射击',
    'ObjSon'          :'车辆是否载人 0：未载人，>0：载哪个棋子（ID）',
    'ObjBlood'        :'当前几个车（班） 1～3',
    'ObjStep'         :'当前机动力值',
    'C2'              :'当前弹药数',
    'A3'              :'当前导弹数',
    'UserID'          :'原控制员ID',
    'UserNewID'       :'新控制员ID 0：未交换控制',
    'ObjPos'          :'棋子原来在哪格',
    'ObjNewPos'       :'棋子移动到了哪格，未移动则记录当前格',
    'AttackID'        :'此ID关联原数据库中的Caijue表，用于查询裁决过程，因此原数据库的Caijue表需要保存 0：未射击',
    'TarID'           :'被射击的棋子ID 0：未射击',
    'TarLost'         :'被射击的棋子损失车（班）数 0：无效，1～3：损失车（班）数',
    'TarKeep'         :'被射击的棋子是否被压制 0：未压制，1：压制',
    'TarBlood'        :'被射击后棋子剩余车（班）数  0～3',
    'FireID'          :'开火图片，仅用于回放中显示效果，何种武器通过AttackID查Caijue表 0：未射击',
    'ObjInto'         :'上车则记录该车ID 0：无动作，>0：上哪辆车（ID）',
    'ObjOut'          :'下车则记录该车ID 0：无动作，>0：从哪辆车下来（ID）',
    'ObjKeepCancel'   :'此列只记录是否进行了移除压制动作，不用于回放，回放通过判断状态数据即可 0：无动作，1：移除压制',
    'CityTake'        :'0：无动作，1：执行占领',
    'CityID'          :'如果有数据，则该格ID显示被占领 0：无占领',
    'KeepRemoveArr'   :'被移除压制的棋子ID',
    'TireRemoveArr'   :'被移除疲劳的棋子ID',
    'JmArr'           :'间瞄计划格',
    'JmColor'         :'移除某一方间瞄计划时需要用',
    'JmResult'        :'间瞄裁决结果',
    'JmObjResult'     :'间瞄所造成的单位损失',
    'Scenario'        : 'Scenario',
    'Area'            :'地区 河北',
    'Level'           :'比赛级别 预赛',
    'Scale'           :'比赛规模 个人',
}

caijue = {
    'AttackID'        :'裁决ID 和RoomRecord表里的AttackID关联',
    'RoomID'          :'推演室ID',
    'Huihe'           :'阶段ID',
    'RoundColor'      :'阶段所属方',
    'StageShoot'      :'最终射击阶段 直瞄射击 0：不是，1：是 间瞄射击 间瞄计划ID',
    'Yanhu'           :'掩护射击 0：不是，1：是',
    'ObjID'           :'射击单位',
    'ObjName'         :'射击单位名称',
    'ObjColor'        :'射击单位所属方',
    'ObjA1'           :'行进间射击能力 0：无，1：有',
    'ObjType'         :'单位类型 1：人员，2：车辆',
    'ObjKeep'         :'射击单位被压制状态 0：未被压制，>0：被压制的阶段',
    'ObjNum'          :'射击单位车/班数 间瞄射击表示炮数',
    'ObjPass'         :'射击单位状态 1：一级疲劳，2：二级疲劳',
    'TarID'           :'目标单位',
    'TarUserID'       :'目标所属用户ID',
    'TarName'         :'目标单位名称',
    'TarColor'        :'目标单位所属方',
    'TarB0'           :'目标单位装甲防护 0：无，1：轻型，2：中型，3：重型，4：复合',
    'TarType'         :'目标单位类型 1：人员，2：车辆',
    'TarHide'         :'目标单位是否掩蔽 0：否，1：是',
    'TarKeep'         :'目标单位被压制状态 0：未被压制，>0：被压制的阶段',
    'TarPass'         :'目标单位状态 1：机动中，2：行军中',
    'TarStack'        :'目标单位是否堆叠 0：否，1：是',
    'WeaponID'        :'使用的武器ID',
    'WeaponF1'        :'使用的武器火力线',
    'WeaponName'      :'使用的武器名称',
    'Dist'            :'射击距离',
    'EleDiff'         :'高差 直瞄射击用这列表示高差1-8 间瞄射击用这列表示表示战斗结果修正随机数',
    'AttackLevel'     :'攻击等级 1到10 间瞄射击用这列表示火力散布裁决结果 null：命中，0-N：散布N格',
    'TarPos'          :'目标单位所在坐标',
    'TarHex'          :'目标单位所在格地形 51：居民地，52：丛林地',
    'RandomNum1'      :'战斗结果表随机数 直瞄射击用这列表示战斗结果表随机数 间瞄射击用这列表示火力散布裁决随机数',
    'Result1'         :'战斗结果 null：无效，0：压制，1-3：消灭车/班数',
    'RandomNum2'      :'战果修正随机数 直瞄射击用这列表示战果修正随机数 间瞄射击用这列表示战斗结果裁决随机数',
    'Diff'            :'战果修正值',
    'Result'          :'最终战果',
    'Keep'            :'是否压制',
    'Kills'           :'是否消灭',
    'TarLost'         :'目标损失的车/班数',
    'TarNum'          :'目标还剩几个单位',
    'Flag'            :'裁决类型 0：直瞄射击，1：间瞄射击',
    'UserRead'        :'观摩者是否看到',
    'Scenario'        : 'Scenario',
    'Area'            :'地区 河北',
    'Level'           :'比赛级别 预赛',
    'Scale'           :'比赛规模 个人',
}
object = {
    'ID'          :'棋子ID 每一场比赛不同',
    'Room'        :'推演室ID',
    'UserID'      :'用户ID',
    'GameName'    :'用户昵称',
    'GameColor'   :'推演方',
    'Army'        :'编号',
    'ObjName'     :'棋子名称',
    'ObjDataID'   :'棋子模型ID',
    'ObjSup'      :'车上步兵ID',
    'ObjSon'      :'能搭载哪些模型',
    'ObjSonNum'   :'车上步兵棋子数量',
    'ObjSonName'  :'车上步兵名称',
    'ObjSpace'    :'最多搭载几个步兵',
    'ObjFlag'     :'棋子颜色',
    'ObjPos'      :'当前所在格',
    'ObjIco'      :'三维图标',
    'ObjIcon'     :'二级图标',
    'ObjType'     :'棋子类型：1 人员 2 车辆',
    'ObjRot'      :'当前角度',
    'ObjStep'     :'机动力上限',
    'ObjStepMax'  :'当前机动力',
    'ObjPass'     :'人员 1 1级疲劳 人员 2 2级疲劳 车辆 1 行军中',
    'ObjBlood'    :'当前车/班数',
    'ObjBlood2'   :'初始的车/班数',
    'ObjKeep'     :'第X阶段被压制过',
    'ObjSee'      :'ObjSee',
    'ObjHide'     :'1 掩蔽中',
    'ObjAim'      :'ObjAim',
    'ObjValue'    :'车/班分值',
    'ObjValue2'   :'是否指挥车 0否，1是',
    'ObjMoney'    :'是否上过车 上过车的步兵原始ID在这',
    'ObjRound'    :'第X阶段机动过',
    'ObjAttack'   :'第X阶段射击过',
    'ObjDate'     :'ObjDate',
    'ObjRadar'    :'是否夺控过 1 夺控过',
    'ObjRes'      :'ObjRes',
    'ObjRes2'     :'ObjRes2',
    'Slope'       :'Slope',
    'A0'          :'A0',
    'B0'          :'装甲级别 0 无装甲 1 轻型 2 中型 3 重型 4 复合',
    'A1'          :'行进间射击能力 0无 1 有',
    'A2'          :'A2',
    'A3'          :'当前导弹数',
    'A4'          :'A4',
    'A5'          :'A5',
    'B1'          :'B1',
    'B2'          :'B2',
    'B3'          :'B3',
    'B4'          :'B4',
    'B5'          :'B5',
    'C0'          :'C0',
    'C1'          :'图标显示大小 0小，1大',
    'C2'          :'当前炮弹数',
    'C3'          :'C3',
    'D0'          :'当前道路行军上限（走到不同的道路上会变）',
    'D1'          :'车辆道路行军消耗机动力值 每几格消耗1个机动力',
    'D2'          :'D2',
    'D3'          :'D3',
    'E0'          :'炮弹上限 0 表示棋子是炮兵',
    'E1'          :'E1',
    'E2'          :'E2',
    'F0'          :'常规弹药消耗量 每次射击',
    'F1'          :'F1',
    'F2'          :'F2',
    'F3'          :'F3',
    'R1'          :'步兵攻击力（当前格）',
    'R2'          :'步兵攻击力（相临格）',
    'R3'          :'步兵攻击力（隔1格）',
    'R4'          :'步兵攻击力（隔2格）',
    'R5'          :'R5',
    'S1'          :'观察距离 对人',
    'S2'          :'观察距离 对车',
    'S3'          :'S3',
    'S4'          :'S4',
    'S5'          :'S5',
    'Wz'          :'关联的武器ID',
    'Scenario'    :'Scenario',
    'Area'        :'地区 河北',
    'Level'       :'比赛级别 预赛',
    'Scale'       :'比赛规模 个人',
}